#!/usr/bin/env zsh




wget https://github.com/squidfunk/mkdocs-material/archive/refs/heads/master.zip

unzip master
rm master.zip
rm -rf ./material
mv ./mkdocs-material-master/material ./material
echo "swiftcoder.site" > material/CNAME
rm -rf mkdocs-material-master

mkdocs build

git add .
git commit -a -m "update"
git push origin master
