site_name: Swift Coder - Artur Gurgul
docs_dir: articles
site_dir: docs

site_url: https://swiftcoder.site/

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#revision-date
repo_url: https://github.com/swiftcoder-site/swiftcoder-site.github.io
edit_uri: edit/master/articles/

nav:
    - Home: index.md
    # - Design principles:
    #   - SOLID Principles:
    #     - SRP - Single Responsibility Principle:

    - Design patterns: 
      - Creational patterns:
        - Singleton: design-patterns/creational-patterns/singleton.md
    - Testing: 
      - Dependency injection: testing/dependency-injection.md
    # - Code snippets: index.md
    - SDK: 
      - Threading: sdk/threading.md
      - Theming with View Modifiers: sdk/view-modifiers.md

# theme:
#     name: readthedocs


theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  name: null
  language: en
  font: null
  icon: null
  custom_dir: 'material'

  include_search_page: false
  search_index_only: true

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
# pip3 install pygments
# pip3 install pymdown-extensions --force

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences

markdown_extensions:
    - pymdownx.highlight:
        use_pygments: true
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - codehilite